### ISSUE TITLE
99 Bottles Text does not match the most recent challenge's.

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [Mego/Seriously#10]
Dude. Fix yo' language so we can use it for <s>evil</s> eval! Muahahaha!

**Comment by Mego** [comment]
HIGHEST PRIORITY

**Comment by Mego** [comment]
Fixed with https://github.com/Mego/Seriously/commit/7237fe91cbfc0a94e142ee155cdb553eb88196fa
