### ISSUE TITLE
split for lists not supported

### ISSUE THREAD

**Issue by TanMath** [Mego/Seriously#20]
Can you possibly add a split() function to Seriously? it would help with various different challenges on code golf.

**Comment by TanMath** [comment]
@Mego what character will be used for the splig function. It should be relatively easy to implemenf and I can help you if you need it.

**Comment by Mego** [comment]
`s` does this as of https://github.com/Mego/Seriously/commit/5618b69a8e4eed506f3e47f525a0d781fb7a9dba but I forgot to close this
