### ISSUE TITLE
index function is not working

### ISSUE THREAD

**Issue by TanMath** [Mego/Seriously#21]
Based in the commands.txt, ¡ is supposed to be the character to do the index function (like b.index(a)) but when I tried it, it didn't work. For this code:

`[1,2,3]2¡`
 I got an output of:
    `2
    [1,2,3]`

Clearly, this is not expected. In the description, the ¡ character is said to "pop a,b: push a string representing a in base b" So even the description is messed up. Clearly this is a bug.

**Comment by Mego** [comment]
`161 (í): pop a,[b]: push [b].index(a) (0-based, -1 if not found)`
