### ISSUE TITLE
References to O persist

### ISSUE THREAD

**Issue by ararslan** [Mego/Seriously#3]
Some files (probably just those based on files from the O programming language) still make references to O. For example, from ide.py:

    if __name__ == '__main__':
        print('Compiling O...')
        check_call(['gcc', 'o.c', '-DIDE', '-o', 'o-ide', '-lm'])
        print('Starting server...')
        app.run(host='0.0.0.0',port=80)

**Comment by Mego** [comment]
Fixed in https://github.com/Mego/Seriously/commit/bf1ed7a82638592622f31ef415a3328bf5a386b0
