### ISSUE TITLE
Duplicate doesn't work on a zip

### ISSUE THREAD

**Issue by Sherlock9** [Mego/Seriously#71]
After zipping two lists with `Z`, `;` doesn't work. I need to use `Z♂#;` because just `Z#;` doesn't convert the inside lists to lists.

**Comment by Mego** [comment]
That probably will affect all generators. I'll work on a fix that doesn't just convert them to lists before duplication.

**Comment by Sherlock9** [comment]
@Mego Thanks for your quick response. Let me know when you can work on issue #72 as well.

**Comment by Mego** [comment]
Though this is fixed, I'm not entirely satisfied with the resolution. I'm going to keep playing with it to see if I can make it work better.
