### ISSUE TITLE
Numeric list commands that don't work on a list of complex numbers

### ISSUE THREAD

**Issue by Sherlock9** [Mego/Seriously#73]
See this code here: http://actually.tryitonline.net/#code=zqM&input=Wy0xNS4yMSswLjhqLCAxMC4xLTAuM2osIC0wLjA3KzIzLjU1al0

**Comment by Sherlock9** [comment]
A more complete list of commands that don't work with lists of complex numbers:
æ - mean([a])
σ - cumulative sums of [a]
µ - root-mean-square of [a] (this may not apply well to complex numbers)

**Comment by Mego** [comment]
No repro on `σ`, but I see the source of the issue with mean and RMS. Those will be fixed shortly.

**Comment by Sherlock9** [comment]
Ah, you were right about `σ`. I misread the results when checking. Thanks for the fixes.
