### ISSUE TITLE
Printing without trailing newline?

### ISSUE THREAD

**Issue by GolfingSuccess** [Mego/Seriously#76]
I want a feature so that I can print without a trailing newline, like `sys.stdout.write`. Right now, using `.` doesn't suffice. Is there any such function alerady?

**Comment by Mego** [comment]
This will be added soon.

**Comment by GolfingSuccess** [comment]
In Python 3, you can also use `print("anything", end = "")` or something like that (NOT in Python 2).

**Comment by Mego** [comment]
@GolfingSuccess If you look at the commit, that is exactly how it is implemented.

**Comment by GolfingSuccess** [comment]
Oh, is 3.6 released? I got to update Python! (Also, I should use 2.7.13 too).

**Comment by Mego** [comment]
@GolfingSuccess TIO hasn't been updated yet.
