### ISSUE TITLE
Excess input fails.

### ISSUE THREAD

**Issue by GolfingSuccess** [Mego/Seriously#77]
I dunno why, but, whenever I have something in STDIN that I don't use, the program errors out.

Try [this](//actually.tryitonline.net#input=PGVycm9yPjxlcnJvcj4&debug=o) one, for example, to get what I'm saying.

**Comment by Mego** [comment]
That's because Python can't parse the input you're providing. This is not a bug.

**Comment by GolfingSuccess** [comment]
@Mego ...don't get what do you mean? Does it need to parse it at all?

**Comment by Sherlock9** [comment]
What you are trying to parse in that example is not a string, a number, a list, a tuple, a set, or a dict. Python has no syntax that starts with `<` and ends with `>` . Python cannot use that input, so you get an error.

**Comment by GolfingSuccess** [comment]
@Sherlock9 Do you mean that the input is `eval`'d before running the program?

**Comment by Mego** [comment]
@GolfingSuccess Yes, that is exactly what happens. It's like Python 2's input. Additionally, when run on TIO, only literals are allowed in input (so you can't have `range(5)` as your input).

**Comment by GolfingSuccess** [comment]
@Mego Interestingly enough, `-h` and `--help` do not work, at least on TIO Nexus. What option is it that triggers safe mode???
