### ISSUE TITLE
NUL - HALT_AND_CATCH_FIRE

### ISSUE THREAD

**Issue by Blacksilver42** [Mego/Seriously#89]
Cause the interpreter to crash, just for fun. I'm sure we'll find a use for this.

**Comment by Mego** [comment]
No repro for non-NUL control codes. NUL causes issues with reading code from CLI via `-c`, but that's to be expected. What code were you using that caused a crash?

**Comment by Blacksilver42** [comment]
No, this is a feature request.

**Comment by Mego** [comment]
Oh. Then no.
