### ISSUE TITLE
↨ - set SORTFLAG; ▬ - get SORTFLAG

### ISSUE THREAD

**Issue by Blacksilver42** [Mego/Seriously#90]
## `↨` (17)
* pop **a**
* Set a variable I'll call `SORTFLAG` = **a**

`SORTFLAG` is used with [`↑↓→←`] to determine how sorting is done. 
For example:

0. sort strictly by value. (default)
1. sort by value, strings first
3. sort by value, strings last
etc...

`-f` `--sortflag`: set starting SORTFLAG.

## `▬` (16)
* push `SORTFLAG`

**Comment by Mego** [comment]
This seems too complicated and not useful enough. I'm planning on implementing a sort-by-key command where a function and an iterable are input, and the iterable is sorted by the TOS from the function called with each element.
