### ISSUE TITLE
Seriously Penguin

### ISSUE THREAD

**Issue by vihanb** [Mego/Seriously#91]
![seriously](https://user-images.githubusercontent.com/15314511/34022778-27148466-e0f6-11e7-9653-2ae38269e882.png)

Very serious penguin 10/10 icon

**Comment by vihanb** [comment]
I can provide svg

**Comment by Mego** [comment]
This is the stuff of nightmares. -1.

**Comment by vihanb** [comment]
D: penguin are not nightmare

**Comment by Mego** [comment]
Not in general, but that one is.
